GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json
###

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
     "name":"khangaikhuu",
    "email":"khangaikhuu@gmail.com",
    "createdOn":"2010-01-01",
    "lastLogin": "2023-02-18"
}

###
DELETE http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
      "id": "6411426186572a1bc48bcaf6"
}

###

PUT http://localhost:8080/updateUser HTTP/1.1
Content-Type: application/json

###


GET http://localhost:8080/user?id=6411428d1f1b35abccda7b6f HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/userByEmail?email=khangaikhuu@gmail.com HTTP/1.1
Content-Type: application/json

###


GET http://localhost:8080/userGetEmail?email=khangaikhuu@gmail.com HTTP/1.1
Content-Type: application/json

###

# PUT http://localhost:8080/employee HTTP/1.1
# Content-Type: application/json

# {
#     "empNo":499999,
#     "lastName": "Jamiyan",
#     "gender":"F"
# }